# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lCTipiLhKROipfOA52GTaPfKhS4z_Xzp
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Generating 12,000 random numbers
random_numbers = np.random.randn(12000)

# Plotting Histogram
plt.figure(figsize=(10, 6))
sns.histplot(random_numbers, kde=True, color='skyblue')
plt.title('Histogram with KDE')
plt.xlabel('Value')
plt.ylabel('Frequency')
plt.show()

# Plotting Boxplot
plt.figure(figsize=(10, 6))
sns.boxplot(y=random_numbers, color='lightgreen')
plt.title('Boxplot')
plt.ylabel('Value')
plt.show()

# Plotting Violin Plot
plt.figure(figsize=(10, 6))
sns.violinplot(y=random_numbers, color='salmon')
plt.title('Violin Plot')
plt.ylabel('Value')
plt.show()

# Plotting Swarm Plot (for smaller datasets)
sampled_data = np.random.choice(random_numbers, 1000) # Sample 1000 points for swarm plot
plt.figure(figsize=(10, 6))
sns.swarmplot(data=sampled_data, color='purple')
plt.title('Swarm Plot')
plt.ylabel('Value')
plt.show()

# Plotting ECDF (Empirical Cumulative Distribution Function)
plt.figure(figsize=(10, 6))
sns.ecdfplot(random_numbers, color='orange')
plt.title('Empirical Cumulative Distribution Function (ECDF)')
plt.xlabel('Value')
plt.ylabel('CDF')
plt.show()

# Plotting Heatmap
plt.figure(figsize=(10, 6))
sns.heatmap(random_numbers.reshape(100, 120), cmap='coolwarm')
plt.title('Heatmap')
plt.xlabel('Column')
plt.ylabel('Row')
plt.show()